### ISSUE TITLE
Финансовая помощь

### ISSUE THREAD

**Issue by wasjawojasja** [free-belarus/info#12]
# Финансовая помощь

[Отправить заявку на получение помощи](https://docs.google.com/forms/d/e/1FAIpQLSc1S_MetSIdBpBerkcKSTowmBB5MKRvM4nmP-e3fOM6I5HOzg/viewform) от инициативы [BY_help](https://www.facebook.com/BYhelpBY/)

# Кампании по сбору средств и предметов первой необходимости

- [Поддержка жертв насильственных репрессий в Беларуси](https://www.facebook.com/donate/1123543824684874) — собирает [Alexey Leonchik](https://www.facebook.com/lavoncyk)
- [Поддержка тех, кто потерял работу, уволился, объявил забастовку](https://www.facebook.com/donate/1355362374670129) — собирает [Liudmila Pestun](https://www.facebook.com/mila.pestun)
- [Сбор предметов первой необходимости](https://t.me/redcrossby/3) — собирает [Служба Красного Креста](https://redcross.by/)
- [Медпомощь для пострадавших во время мирных демонстраций](https://imenamag.by/projects/help-for-injured) — собирает [проект Имена](https://imenamag.by/)
- [Belarus Solidarity Foundation — Support Belarusian in strike](https://www.facebook.com/donate/759400044849707/759406901515688) — собирает [Alexis Kendoo](https://www.facebook.com/alexis.kendoo)

---

За список спасибо [belarushelp.org](https://belarushelp.org/).

**Comment by wasjawojasja** [comment]
Список находится в файле [/docs/donations.md](https://github.com/free-belarus/info/edit/master/docs/donations.md).

**Comment by nikita-leonov** [comment]
@wasjawojasja на https://www.belarus97.pro для ByHelp еще указан PayPal. В США в связи с политикой приватности Facebook многие стали от него отказываться и не смогут пожертвовать через Facebook. 

Есть один какой-то не понятный момент. На https://www.belarus97.pro указан адрес для PayPal https://www.paypal.com/pools/c/8qk6aQYmmt На instagram недавно распространялась другая ссылка https://www.paypal.com/pools/c/8rjj4ZxCNs Создано одним и тем же человеком вроде. Описание похожее. Собранные суммы разные. Было бы интересно связаться с Алексеем и разобраться что это такое и какую ссылку добавлять.

**Comment by wasjawojasja** [comment]
@nikita-leonov спасибо! Попробуем выяснить.

**Comment by wasjawojasja** [comment]
Сооснователь Sports.ru Дмитрий Навоша создал Фонд солидарности для помощи забастовщикам и белорусским силовикам, которые перешли на сторону протестующих.

В интервью подкасту «Что случилось» Дмитрий Навоша рассказывает, как он стал российским координатором действий против Александра Лукашенко.

https://mdza.io/5l62J2FyGr4

**Comment by nikita-leonov** [comment]
Не многие компании могут вносить пожертвования через каналы предоставленные https://www.belarus97.pro Самый лучший способ для пожертвований для больших компаний будет http://imenamag.by которые имеют надлежащий юридический статус.

**Comment by user20200829** [comment]
Ещё:
* [protectbelarus.org](http://protectbelarus.org/) - помощь сотрудникам силовых ведомств, лишившимся работы из-за отказа выполнять преступные приказы
* [От инициативы "Честные Люди"](https://help.honest-people.by)

Также предлагаю оформить в виде таблицы, например:

| Инициатива | Кто собирает | На кого направлена | Как оказать помощь | Как получить помощь | Информация о фонде |
| -- | -- |-- | -- | -- | -- |
| [BYSOL](https://www.facebook.com/donate/759400044849707/) | Alexis Kendoo | Пострадавшим и лишившимся работы из-за политических репрессий | Через Facebook, PayPal, Revolut (cм описание фонда) | Заполнить форму запроса (ссылка в описании фонда) |  [2020-08-21 Статья на kyky.org o paботе фонда](https://kyky.org/money/belarusy-sobrali-1-600-000-dlya-bastuyuschih-no-kto-i-kak-poluchaet-eti-dengi-razobralis); [2020-08-20 Статья на tut.by о работе фонда](https://finance.tut.by/news697333.html); [2020-08-18 Сообщение по теме на канале Белсат](https://t.me/belsat/13672); [FB Андрея Стрижака](https://www.facebook.com/andrej.strizhak)

Готов переделать в предложенный формат. Можете закинуть на меня задачу - начну переделывать.

**Comment by wasjawojasja** [comment]
@user20200829 да, без вопросов, всё по делу.

**Comment by user20200829** [comment]
На текущий момент считаю задачу закрытой. Или что-то осталось?

**Comment by user20200829** [comment]
Добавить:
* [MediaSOL](https://www.gofundme.com/f/mediasol)

**Comment by wasjawojasja** [comment]
@user20200829 думаю да, можем закрывать задачу, спасибо большое! Завтра гляну ещё раз, уже мало сил адекватно анализировать.

**Comment by user20200829** [comment]
Добавить:
* [INeedHelpBy](https://t.me/vybory_smotri/7437)

**Comment by wasjawojasja** [comment]
Закрываю задачу.

@user20200829 спасибо за помощь! Если захотите добавить ещё что-то — можно добавлять и без issue, или воскресить эту задачу — она же никуда не исчезнет.
