### ISSUE TITLE
Ролик «Забастовка или всё по техпроцессу» (МТЗ)

### ISSUE THREAD

**Issue by wasjawojasja** [free-belarus/info#13]
Предлагаю сделать вирусную рекламу по мотивам [шикарного плаката с мтз](https://t.me/meduzalive/31214).

# Забастовка или «всё по техпроцессу»

Завод до сих пор жив благодаря инициативе рабочих, что бы тебе не лили в уши все 26 лет.

Нет резца — едешь за ним на Ждановичи. Начальник не выдал спецовки — хуй с ним, куплю на рынке. А потом он же просит тебя остаться после смены, ведь нужно выполнить план. Получаешь расчётный и понимаешь: снова наебали. Жалуешься в профсоюз, но заранее знаешь ответ. Случилась производственная травма — оформляешь бытовую, потому что «вы же всё понимаете».

## Правда, заебало?

Самый доступный способ повлиять на власть — это забастовка. Не нужно идти на площадь и стучать каской по плитке. Приди на участок и работай по техпроцессу: 

- Для работы мало света — вкрутите лампочки, блять!
- Позовите наладчика, пусть настроит ебучий станок — это не моя работа!
- Выдайте мне спецодежду — вы меня сами ебёте за охрану труда!
- Заебало работать на станке, на который с крыши капает вода!
- Я — фрезеровщик! Какого хуя я должен работать шлифовальщиком?

---

Требуй соблюдения каждого пункта техпроцесса. Это твоё законное право. Как и право на достойную зарплату и честные выборы, которые у тебя украли.

Хочешь присоединиться, но боишься, что уволят? Помни: ни один пиздючий идеолог не станет за станок.

---

# Конституция Республики Беларусь
## Статья 41

>Граждане имеют право на защиту своих экономических и социальных интересов, включая право на объединение в профессиональные союзы, заключение коллективных договоров (соглашений) и право на забастовку. Принудительный труд запрещается, кроме работы или службы, определяемой приговором суда или в соответствии с законом о чрезвычайном и военном положении.

**Comment by wasjawojasja** [comment]
1. Первая часть невменяемым голосом.
2. Вторая часть обычным голосом.

**Comment by wasjawojasja** [comment]
# Текст для раскадровки

1. Забастовка или «всё по техпроцессу»
2. Завод до сих пор жив благодаря инициативе рабочих
3. Что бы тебе не лили в уши все 26 лет
4. Нет резца — едешь за ним на Ждановичи. 
5. Начальник не выдал спецовки — хуй с ним, куплю на рынке. 
6. А потом он же просит тебя остаться после смены, ведь нужно выполнить план.
7. Получаешь расчётный и понимаешь: снова наебали. 
8. Жалуешься в профсоюз, но заранее знаешь ответ. 
9. Случилась производственная травма — оформляешь бытовую, потому что «вы же всё понимаете».
10. **Правда, заебало?!**
11. Самый доступный способ повлиять на власть — это забастовка. 
12. Не нужно идти на площадь и стучать каской по плитке. 
13. Приди на участок и работай по техпроцессу.
14. Для работы мало света — вкрутите лампочки, блять!
15. Позовите наладчика, пусть настроит ебучий станок — это не моя работа!
16. Выдайте мне спецодежду — вы меня сами ебёте за охрану труда!
17. Заебало работать на станке, на который с крыши капает вода!
18. Я — фрезеровщик! Какого хуя я должен работать шлифовальщиком?
19. Требуй соблюдения каждого пункта техпроцесса. 
20. Это твоё законное право. 
21. Как и право на достойную зарплату.
22. И честные выборы, которые у тебя украли.
23. Хочешь присоединиться, но боишься, что уволят? 
24. Помни: ни один пиздючий идеолог не станет за станок.
25. **Конституция Республики Беларусь.** Статья 41
26. Граждане имеют право на защиту своих экономических и социальных интересов
27. включая право на объединение в профессиональные союзы, заключение коллективных договоров (соглашений) и право на забастовку. 
28. Принудительный труд запрещается
29. кроме работы или службы, определяемой приговором суда
30. или в соответствии с законом о чрезвычайном и военном положении

**Comment by wasjawojasja** [comment]
Ролик готов: https://t.me/SkarynaPitersky/6 — можно распространять.

**Comment by nile-ch** [comment]
Также дотупен в формате IGTV в инстаграм: https://www.instagram.com/p/CEJ4Zq-hVzG/
