### ISSUE TITLE
Блокировка сайтов *.github.io

### ISSUE THREAD

**Issue by ghost** [free-belarus/info#32]
- [В Беларуси блокируются сайты *.github.io](https://habr.com/ru/news/t/515814/)

Похоже на правду.
Актуально для БТК/byfly - трасерт обрывается на том же узле (asbr9.net.belpak.by).
Через VPN сайт доступен.

**Comment by wasjawojasja** [comment]
Привет! Спасибо за сообщение. 

Мы посовещались и приняли решили полностью отказаться от сайта, причины этому были следующие:

- на поддержку сайта уходят ресурсы, которых сейчас очень мало — сайт реализован плохо и на коленке
- вызывает путаницу для других участников репозитория
- всё равно не доступен для многих жителей РБ

Мы решили сфокусироваться только на обработке информации и хранить её в обычных markdown-файлах, сам GitHub отлично их рендерит.

Если кто-то захочет сделать сайт, то без проблем можно сделать ещё один репозиторий в этой же организации. Возможно кто-то захочет сделать сайт на какой-то другой технологии, на какой-то части информации.

---

Вот старая информация из wiki

# Как работает [сайт](https://free-belarus.github.io/info/)?

У этого репозитория есть сайт, который автоматически собирается при каждом обновлении репозитория, предоставляя информацию для ознакомления людям, которые не умеют и не хотят работать с GitHub.

Сайт построен с помощью [GitHub Pages](https://docs.github.com/en/github/working-with-github-pages/getting-started-with-github-pages), который использует [Jekyll](https://docs.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll). Также нам рекомендовали [Gatsby.js](https://gatsbyjs.org/) или [Next.js](https://nextjs.org/), но мы пытаемся по возможности оставить всё как можно проще и быстрее как в разработке так и в рендере. Это не принципиальный момент — мы открыты к конструктивным предложениям.

Материалы лежат в двух папках:

- `_posts` — стандартная папка для Jekyll, он берёт оттуда материалы автоматически и публикует их в хронику;
- `docs` — созданная папка со статической информацией, чтобы она появилась на сайте — нужно добавить её в файл [`_data/menu.yml`](https://github.com/free-belarus/info/blob/master/_data/menu.yml)

Вся информация появляется [на сайте](https://free-belarus.github.io/info/) не сразу, обычно через несколько минут.

**Comment by wasjawojasja** [comment]
Сайт всё-таки — слишком удобная структура представления визуальных данных, и мы его реанимировали, но иначе. Сайт не привязан к репозиториям, а просто парсит всю информацию из всех репозиториев и представляет в таком виде, в каком мы ему говорим это делать.

Текущий сайт: [free-belarus.info](https://free-belarus.info). Но мы ведём репозитория без ориентации на него, чтобы другие могли использовать информацию в них.
