### ISSUE TITLE
Ролик про достижения Лукашески за 26 лет

### ISSUE THREAD

**Issue by wasjawojasja** [free-belarus/info#33]
# 26 достижений за 26 лет царька

1. **Мизерные пенсии** в размере $100—200
2. **16 лет обещаний** средней зарплаты в $500 
3. **Налог на тунеядство** — отсутствие помощи в трудоустройстве от государства
4. **Массовая безработица** в маленьких городах и сёлах
5. **Отсутствие пособия по безработице** — жалкие $10
6. **Исключение стажа** за обучение, срочную службу, беременность, уход за ребёнком
7. **Отмена льгот** у чернобыльцев и афганцев
8. **Приватизация** советских квартир
9. **Увеличение пенсионного возраста** для обычных трудящихся: с 62 до 65 лет, при средней продолжительности жизни в 69 лет у мужчин
10. Колоссальная **инфляция**, выражающаяся в постоянном росте цен на продукты, топливо и другие товары
11. Постоянные **деноминации и девальвации**: за 20 лет существования белорусская национальная валюта, белорусский рубль, обесценились на 237 595 925 % — двести миллионов процентов!
12. Огромный **госдолг**: от $1,2 млрд в 1994 году к $20 млрд в 2020.
13. **Убыль населения**: от 10,2 млн человек в 1994 до 9,4 млн человек в 2020
14. **Особые льготные условия** для бизнеса друзей: табакерки, дана холдинг
15. **Поддержание** «на плаву» неконкурентноспособных фабрик и заводов **за счёт денег из бюджета** страны, большинство из них работают в убыток.
16. Субботники **и прочие поборы** в школах, садах и государственных организациях
17. **Строительство АЭС**, о которой никто не просил, полностью за кредитные деньги
18. **Изменение Конституции под себя**: отмена ограничения двух сроков правления и расширение полномочий президента
19. Полный **контроль всех органов власти**: от судей до депутатов. Личное назначение на эти должности.
20. Полная **экономическая зависимость** от Российской Федерации
21. Обсуждение и **подписание засекреченных интеграционных карт с Россией** параллельно со сказками про независимость и суверенитет
22. **Игнорирование пандемии коронавируса**
23. **Шантаж непродлением контракта** за отказ от подписки на газеты, похода на парад
24. Постоянные **репрессии**, как на работе, так и в учебных заведениях, за высказывание своего мнения
25. **Массовая трудовая эмиграция**: врачей, учёных, инженеров и других высоко-квалифицированных специалистов, массовая эмиграция молодёжи
26. **Отсутствие честных выборов**: как местных, так и президентских

### Комментарии:

- официально средняя з/п в Минске на июль 2020 года — 1000 руб., $400 по курсу на сегодня

**Comment by wasjawojasja** [comment]
Слишком много информации для одного ролика — в 15 секунд никогда не влезет. Можно, нарезать на 26 кусочков, каждый как маленький тизер сделать, на 15 сек. Либо объединить по 3—4 пункта в ролик и сделать 7 роликов.

**Comment by wasjawojasja** [comment]
С конкретными достижениями — мне кажется, что слабая проработка, у него и повнушительнее «достижения» есть. Но можно и этим заняться, если другого ничего нет. Про политических оппонентов и эскадрон смерти, про пострадавших и умерших сейчас, про его враньё — много чего можно добавить. 

Вот хорошо бы подумать что ещё можно добавить.

**Comment by far-rainbow** [comment]
А почему числа в долларах, а не в тонглесских тугриках? С каких пор внутренний рынок Беларуси стал рынком США, чтобы давать сравнительный анализ именно в долларах?

**Comment by wasjawojasja** [comment]
> А почему числа в долларах, а не в тонглесских тугриках? С каких пор внутренний рынок Беларуси стал рынком США, чтобы давать сравнительный анализ именно в долларах?

Потому что не задавайте идиотских вопросов.

**Comment by wasjawojasja** [comment]
Мы отказались от ролика, потому что не понятно как сделать его быстро и хорошо — это не уместится в 15 или 30 секунд для лёгкого распространения, а на ролик на несколько минут сейчас нет ресурсов, это просто будет неэффективно. Переформулируем задачу в иной медиум — листовки.

https://github.com/free-belarus/agitation/issues/9
