### ISSUE TITLE
Обращения президентов к народу

### ISSUE THREAD

**Issue by wasjawojasja** [free-belarus/info#9]
Расшифровка сообщений к народу, со ссылками на первоисточники.

- законного легитимного президента — Светланы Тихановской 
- незаконного нелегитимнго президентишки — Александра Лукашенко

**Comment by wasjawojasja** [comment]
# Cветлана Тихановская

- Пятница, 14 августа 2020 г — https://t.me/pulpervoi/76

**Comment by na20bb20** [comment]
**Подтвердить свой голос** 
Ссылка на гугл форму  https://forms.gle/uM1XrZSPKPCYKcWo8

**Comment by wasjawojasja** [comment]
Т.к. протест затянулся надолго, то конкретно эта задача не является больше приоритетной, и её поглощает задача публикации новостей как таковых.
